// <auto-generated />
using System;
using BackupApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackupApp.Data.Migrations
{
    [DbContext(typeof(BackupAppDbContext))]
    [Migration("20251129082629_AddSecurityFeatures")]
    partial class AddSecurityFeatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BackupApp.Core.Models.BackupHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackupType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CompressedSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompressionLevel")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilesCopied")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputArtifactPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsedCompression")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("BackupHistories", (string)null);
                });

            modelBuilder.Entity("BackupApp.Core.Models.BackupSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BackupSettings", (string)null);
                });

            modelBuilder.Entity("BackupApp.Core.Models.BackupTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackupType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompressionLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptionPasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastBackupTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastFullBackupTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxAgeDays")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxVersions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetentionPolicyType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScheduleDayOfMonth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScheduleDays")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduleTime")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseCompression")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseEncryption")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BackupTasks", (string)null);
                });

            modelBuilder.Entity("BackupApp.Core.Models.BackupHistory", b =>
                {
                    b.HasOne("BackupApp.Core.Models.BackupTask", "Task")
                        .WithMany("History")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("BackupApp.Core.Models.BackupTask", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
